# @package _global_

wandb:
  project: "mipt-brain-tumor-segmentation"
  entity: null

max_train_epochs: 50
validation_intervals: 1
initial_learning_rate: 1e-4
weight_decay: 1e-5
inference_roi_size: [128, 128, 64]